version: '3'
services:
    backend:
        build: .
        ports:
            - "3001:3001"
        environment:
            DB_HOST: "localhost"
            DB_USER: root
            DB_PASSWORD: ""
            DB_NAME: medical_consultation
